use teste;
INSERT INTO cadfun VALUES 
(8, 'ANA BASTOS', '5', 'PROGRAMADOR', 1350.00); 
SELECT * FROM cadfun WHERE CODFUN = 8;
UPDATE cadfun SET SALARIO = 2300.56 WHERE CODFUN = 8;
SELECT * FROM cadfun WHERE CODFUN = 8;
SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';
UPDATE cadfun SET DEPTO = '3' WHERE NOME = 'ANA BASTOS';
SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';
UPDATE cadfun SET SALARIO = SALARIO * 1.10 WHERE NOME = 'ANA BASTOS';
SELECT * FROM cadfun;
