use teste;
SELECT * FROM cadfun WHERE NOME LIKE 'A%';
SELECT * FROM cadfun WHERE NOME LIKE '_A%';
SELECT * FROM cadfun WHERE NOME LIKE '%AN%';
SELECT * FROM cadfun WHERE SALARIO LIKE '%6';
SELECT * FROM cadfun WHERE SALARIO LIKE '_5%2';
SELECT * FROM cadfun WHERE NOME NOT LIKE '%AN%';