use teste;
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE  '11%';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '%8%';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '_0%';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '1_%_%';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '%6';
SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '_1%6';