use teste;
SELECT * FROM cadfun;
SELECT NOME, FUNCAO FROM cadfun;
SELECT NOME, CODFUN FROM cadfun WHERE DEPTO = '3';
SELECT NOME, SALARIO FROM cadfun ORDER BY NOME;
SELECT NOME, SALARIO FROM cadfun ORDER BY NOME DESC;
SELECT DEPTO, NOME FROM cadfun ORDER BY DEPTO, NOME DESC;
SELECT NOME FROM cadfun WHERE DEPTO = '3' ORDER BY NOME;