use teste;
ALTER TABLE cadfun ADD FILHOS SMALLINT;
SELECT NOME, FILHOS FROM cadfun;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NOT NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT (FILHOS IS NULL);