use teste;
INSERT INTO cadfun VALUES 
(9, 'MARCELO SOUZA', '5', 'VENDEDOR', 1500.50);
select * FROM cadfun WHERE CODFUN = '9';
SELECT DISTINCT DEPTO FROM cadfun;
DELETE FROM cadfun WHERE DEPTO = '5';
SELECT DISTINCT DEPTO FROM cadfun;
DELETE FROM cadfun WHERE NOME = 'MARCELO SOUZA';
SELECT * FROM cadfun;